version: 2.1


orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.2.5

jobs:
  tcb-test:
    docker:
      - image: cimg/node:16.14.2
      #- image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - run: 
          name: "preparation"
          command: npm install testcafe;
                   npm install dayjs;
                   npm install testcafe-reporter-html;
                   mkdir -p ./reports;
      - run: npx testcafe chrome:headless No1_2_3.ts --reporter html:reports/html_report.html #,xunit:/reports/xml_report.xml
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
          destination: artifact-file

workflows:
  e2e-test:
    triggers:
      - schedule:
          cron: "*/15 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - tcb-test
