version: 2.1


orbs:
  node: circleci/node@4.7
  browser-tools: circleci/browser-tools@1.2.5

jobs:
  tcb-test:

    docker:
      - image: cimg/node:16.14.2
      #- image: cimg/node:lts-browsers

    steps:
      - checkout
      - browser-tools/install-chrome
      - run: 
          name: "preparation"
          command: npm install testcafe;
                   npm install dayjs;
                   npm install testcafe-reporter-html;
                   mkdir -p /tmp/test-results;
      - run: npx testcafe chrome:headless No1_2_3.ts --reporter html:/reports/test-results/html_report.html,xunit:/reports/test-results/xml_report.xml
      - store_test_results:
          path: /reports/test-results
      - store_artifacts:
          path: /reports/test-results
          destination: artifact-file

workflows:
  e2e-test:
    jobs:
      - tcb-test